language: java
sudo: true
addons:
  ulimit:
    nofile: 1048576
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: UwPvUox14dxHIcuq+eV3xwzv1BtQpdibMqA5sM9cFdD23yoXC18XfoVk1FL8X9INX2uFddZ6zLHOQwDuvj1WbBphS6yaSOVj5YnM6osrSTgvjxVuyT04sjDfnY8jpgmrfLhqAuVxjM11PwEdn3H+sPXdXGLpLX8sp6VD+FJr8JqzhDcLvJfbJ0ucTmSCUUbX2+N25YNL0HpylzmPhjzRxf4Xekzdq+wkWN+pYAs9vQSxr4nd/4KVXY1WLTU+JqC9KnDdQPvY0OE6LhMFWV7WarBsll65hA7C0IOccx7gTrUTY3GRy3uE41uVqKxJJyZFx5qBn02dtuKSmOHvbU9XSxoAXxFEOix2tEyzRTwaNedTFVwyBJU3vmwlJx4QHiXGgzp6qHGWirGC4tFYbfcOo6nybcIJKdSHxcGFS+uONgWn4jSVU329N7GYpQ9p8n7UNljLeSiD4b04VgfmLxnOBynFpVCNJr+iBwXpI5RXWD7PPPrJJ+duSq4VJ6eYtC6p1EDfQCcuPFRb+BZdktvPCDUte+HgdRgLk+M1Cwx4gH9rL1sSeUyZnw3oUl+9dihq9vCiOtPTJVQ1SEw9qA7h16YlSPjJoIahLm9dX5/fN/bqdxG2VqoDW5SzozWd/S4OYeJn/uDKBdd8vuGEm7gR0yD9doI8LQ6l8JqGjTBxveM=
  - secure: SdztqE9uGoNqSUv2NebbM69rvcdwiFCehGU0oq7IB+ViBVCBGi1pLod70UAvtBiAeQF3gUe8kXdv0S+Whj2c2qdEBnRKlDVTScxZbdys0V8KOTmFLI9W1dkowmH86dNNDg94sSS+DrOXdj5qlpBXktWlIcBxTJkAXwJqSVOluQvIhXyrX1oJ/4+0r011rW+6i+odkmR0kBon5unhiYC9/FwgFS9TkwEpQWvIlIFbbGMqt4uMEJ/PzDmZTxR91nDY7zhpQl/I8kfiBHDewwvGHAyCY5LvW4LXqCKZMtKDl7ZMkZVpMF9klazEpxvA+N22XzHviyyI/o4xWs+moD992PmSSYEi+/uK3RMH2YvyNfTy5tgWZ/vb2yu6ZgNJu0xfyNuoReULBbw4Tqh4V9vWBRuVB2JfKxqrP3gz6vMeWxNDMIkCI1v5gl+1+7foQhrSgrTqYa91mQq+8aFaoU7zGt+iaw2iNKrvYE1kIn0r1vNIpDUwuLwjwEwbJK0vwq5zDJJKKQxMyqYljsojEOfROrtt6yKMeZGN6R3kUFIJ1ogYBR+TGndfp8vaFmvwpcObNdPxCT1mWUi/2UME04hoI1RGsZfT9Ej7fcDousACWNLiAV9VUVcXnxEr6L5HAT9KhGVzvvA+MfaeIFU79qt59RsXKxbOhi5OMTZcLnV/+74=
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
jobs:
  include:
  - stage: Tests
    script: "./gradlew test"
  - stage: Deploy to DockerHub
    script:
    - "./gradlew clean jar"
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - export REPO=emcmongoose/mongoose-storage-driver-kafka
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo
      $TRAVIS_BRANCH; fi`
    - export MONGOOSE_VERSION=$(cat build.gradle | grep "mongoose:" | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
    - docker build --build-arg MONGOOSE_VERSION=${MONGOOSE_VERSION} -f docker/Dockerfile
      -t $REPO:$COMMIT .
    - docker tag $REPO:$COMMIT $REPO:$TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO
  - stage: Deploy to GitHub releases
    deploy:
      skip_cleanup: true
      provider: releases
      api_key:
        secure: sCzZ0wCOqzln2oQXkDSPr4Jv77QfktDStWD90y9VSS1lDn1CIRuH8OfUSnfeOmXtuNrMs+ngZw3e7y8QCCYpykancVKOpszgG1pYxcqEdFT9Dj8jzJAJXJZGHrT4E9lHFl3seNH0cFC5BCi2EyHP0Vb1MVBJKwSS0jW8oD9KLdcFaBM45RfTWMt22qHFEI+Bl6ButvRaGmCXgHqQ9fqu2yRaELl+pLT+D44ZS9uhHzoc0htbjnVyQWcCzzLxcAlP6r4YFlTqxznfALf0TRBkgvqqWZ2SnS3u8sd/TQMZAuKwIUFvhHLbiBkfrKH4Ers/gPzoJR8pi1/9CE9gAwHxaGPn2bcxYV/tKnD3B3BweMzairpoHd6um0Uas7EF5E7gj01DsvdgiMfA9PlDeDylzce8rJh5ZNVHGxI6INDDdmDUzo76s9W0d8bYJ5+rz2IfU5rGMaPckaq/b3tBN4yfdHxBAUE1R+OSd2TQ6YP6JP04McpTQb+D6Yo/ealyyt3Jh8Pz8pFq93FN0awUlE6fhIDvTqweBJh4quvGtydzbNukszgro2KMhiqaDuV4pXuIfNwy6KaNZDPui9zgRjDbTWFUlKQq2r0/Gk6tLu2ezPtsdS/KXMJlFkg8TCNN5PlTAlSAu9m8uXzm8/SRfMJvtLQB8pwz/oSjY0UNXHII9KQ=
        file: "./build/libs/mongoose-storage-driver-kafka.jar"
      on:
        tags: true
