language: java

sudo: true

addons:
  ulimit:
    nofile: 1048576

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  # DOCKER_USER
  - secure: "kYrz3MlpeD25DUOq4SYBCD7+jCQo7B75Cyw/l3fYFBVO1VMK5QqbLKKU6Z3OuvtAZMAMip2aY8S4DnAoyLTXrp5k8it7Xia+tzOwam3ecc3OtnAcdamNUTi5HzBHYB6TQ3MrwDWE5P6z2ZIZexohiPdhdnqBrHfHeCwtPShlXQLQ+EHHm1a91uqi8ufgDRN8zVU+W2AuRrykNA5DiTqZRsH4Elbhg7ZKveQwIvkGkUIod2DKxxmuErxCqydiko99fJmxZWg9khKQtcJ3Wos/HsgKqnOxAvXLz0kYO24/TqyodRjvFNDlbfoPBa4bCSeHoP7ptQAsDx+RPb3EfHDMCPrh2AIjaWTTBhbJIVduZFFWmR4bNIJNFGNtgd3notkpJGTshlQe3SKAFvaE+kuCc4O0jJmHmrp2M9D3L4I7GEdjMc+SHo0ZpNTe27ID5L2XzlqBYretRM5vq2W2BS4MvZHVJ9XJVMYAO3WV0BXVaKXyxd61cKI6VjIWKEepw0FgxrE0wltSVTAxo+Mia6ppWvoGsCOX2EXrdy5MtPvFXPpk4bHYdcWQMPZPVRKQzVFyPKX4msiIqKzkr6nwAQISXYs8UrHU+UlWYthwXRNGR01Jfb177Q00hqmKlX6TEqEcLdv+xThzGecPtPdITLKiXMEn9ntAUseCy1rGA2cqKSw="
  # DOCKER_PASS
  - secure: "Q1MIBYcWKLIi+g9AbtecJtr2ctb4joTkLjf8VKwUm9EFafQZVMjOAFMk4Nmgd3/mLOlRBaa8tRdvC9x0/AmWzskWM+6W6CF62c2eYYDsL9lkHRrbx2ILtaLaHsUDjKd8EZBcCbFnWBLyom3173J8YtvdVVvn1iTPLTSdMHcHZFiq/Nlbz/MT8aPfl3fFJgp1/w6/UsFs37Xm9+meXRid6+C968MIURbuJJfaaVSq5PP0EdFyQX1qoeF/B7LR4cnp/wxsMtetvjm1ID/QzXcTlR9IRwAh5w9mP2oLbb+PONVfRPeM5V7zSpwMMB5rgiQWcinCj6eNVBgGXdzGz+SyQdnJz70o8PqSKwBcIHmykgyvf+x6BA0vBOF6aGQMFd/dvlgCssP6VbVTnvaETP1Q0o3Jc5cgW/zUQru+IprDTgm7zPuj4k/sWqJ5NVA9ONP7h10a9zyYE5PHta+UcG5sBt/w3bwV4hY44NsAKVIm1s5RQQIMAZ1r1nra+l1aBXznbCc13bNOHdBRVcAgMf3/Rv7cn1TIn9m7MTYMgPW/PJfdqPJEPXm+qw/q84B5gfPu9GfQ0opNyiix8ity+5hCFt2BhWsge/eFNPTQk1yJm5mROicIMZIzlVfmJmaX465/EF1hkbNLNl/QtRJiKjoAgVvRRE+ANlnTNJBYcVETv34="
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce

jobs:
  include:

  - stage: "Tests"
    script: "./gradlew test"

  - stage: "Deploy to DockerHub"
    script:
    - ./gradlew clean jar
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - export REPO=emcmongoose/mongoose-storage-driver-kafka
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
    - export MONGOOSE_VERSION=$(cat build.gradle | grep "mongoose:" | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
    - docker build --build-arg MONGOOSE_VERSION=${MONGOOSE_VERSION} -f docker/Dockerfile -t $REPO:$COMMIT .
    - docker tag $REPO:$COMMIT $REPO:$TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO

  - stage: "Deploy to GitHub releases"
    deploy:
      skip_cleanup: true
      provider: releases
      api_key:
        secure: sCzZ0wCOqzln2oQXkDSPr4Jv77QfktDStWD90y9VSS1lDn1CIRuH8OfUSnfeOmXtuNrMs+ngZw3e7y8QCCYpykancVKOpszgG1pYxcqEdFT9Dj8jzJAJXJZGHrT4E9lHFl3seNH0cFC5BCi2EyHP0Vb1MVBJKwSS0jW8oD9KLdcFaBM45RfTWMt22qHFEI+Bl6ButvRaGmCXgHqQ9fqu2yRaELl+pLT+D44ZS9uhHzoc0htbjnVyQWcCzzLxcAlP6r4YFlTqxznfALf0TRBkgvqqWZ2SnS3u8sd/TQMZAuKwIUFvhHLbiBkfrKH4Ers/gPzoJR8pi1/9CE9gAwHxaGPn2bcxYV/tKnD3B3BweMzairpoHd6um0Uas7EF5E7gj01DsvdgiMfA9PlDeDylzce8rJh5ZNVHGxI6INDDdmDUzo76s9W0d8bYJ5+rz2IfU5rGMaPckaq/b3tBN4yfdHxBAUE1R+OSd2TQ6YP6JP04McpTQb+D6Yo/ealyyt3Jh8Pz8pFq93FN0awUlE6fhIDvTqweBJh4quvGtydzbNukszgro2KMhiqaDuV4pXuIfNwy6KaNZDPui9zgRjDbTWFUlKQq2r0/Gk6tLu2ezPtsdS/KXMJlFkg8TCNN5PlTAlSAu9m8uXzm8/SRfMJvtLQB8pwz/oSjY0UNXHII9KQ=
        file: "./build/libs/mongoose-storage-driver-kafka.jar"
      on:
        tags: true
