language: java

sudo: true

addons:
  ulimit:
    nofile: 1048576

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: D5HSmhNNt1KnYidiWHq2IDAurNlZ/0GBMEGKwviqDHgKpNb6r6sxHNW9pnTK+CIxaVK6AF26FhNAQ+G0jQcyvKoNjYZBYjdv/jWjHuTy9Dbj5HV+KGtGpzNOlTg+aqx3/aiRRXiHNbxj3F3hjUagavA67ibyTW26mYzjbTNsGchCJ3bclIydEEmNZwmAZDVQdFWEGXq0Qb11mNlJAyN8MxNuep5m/QwvWcnVkkhFtZbgrjunMfoPgHixAKtrhq6e+pvvq2hJ/i+SlF0KzNsqaKHEAC6f8LLYgDpHOP8686XNlyuBLfC18FX4MpI4P1dmPV0p7yO4A7h4rgMc4LCbfq2mXIetyqv2C6BrcSnMzKZ8J5kBe1EjVZlVMBVa2WrWIOBuCXDDHQ6o23Bfy8q6wsQiX3t1K/YvnQx3JaGtPyNVecbQhssLBVDGFJfJNQmF/RJc4ElUoCVtlGk/qnPICeB64d5m4rXF6+HyYDFwlLZbmrndnKTVGzEBh1Fdqi1Ir/8+PpplEw0O5shkRdfcMmI6RQqBqzHeleaVfYSgLBlqVpdgSVfWqh6Flm0ajtBHCWDeKABzmlxgVZTIrM91mtu5h8hWDiqnDROXro0O8d26+rNL05PxHhiB9DjcGwWjvnnaiweQ3/G0jjiOInChXnQvFYFh8i9ou0EVLGfVslc=
  - secure: CUmmf6/m15/8nU10YQ0lvFyJD3QdelxKtn0ztaiXRpUC6OwU5ZfGvmK2ODHewaClm38d9Os+omD4EtdO6ralKaFq0Xgg/mYFa5hp+w4u4p2Q9b7V0GpJjmWUZcH+D80z1VcF1Obswbed0jVirKJUvZBO5djiHetXs3cP8EIdhOvcb+z3zYKJtmo/aUZZECLW/jU14pN1tE2ftMdsDfe73MGnKOnMno7jDD0MgL9xRwbgCzsgrwAExIZ3OdpSU+V3eY6zbzUORf+c9tT+tLBduAEMh0AxXjo4Z0tDPnSvFJFJpiIWKfXDaJejm8l3WpeFMlem4RJibt3/zT/QpayqPoZxR0tUA2mKAZ9HeslTJ9qjjJyaum9/USsdIoJC9X1k69GOTN+t6KwI20wRnQ329auMLrDEyVrAMl+8U2nxm5EWN6jOapOd5SAk9YV04VkddQfwvYka9Q1S9E00RmT71bYLGyqo6gukJocNc3rIQqYQfnBq3dYUOz4ehGWK6COvVq6cIVWkq/+Fz1X/uCwrRY23dVsaUHZxVrOqUF0Lx4jegDD83K55yEbhawSTawCHS94q9wOHHrdfMIm7/10LzsyvErN3B8NwbbxyEii+gjmchIUTyeYAmHTgNdS7giKiZpdmIS7URvST4lvh0ncZwj7oOjj6asUm+hVRc+wFvoQ=
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce

jobs:
  include:

  - stage: "Tests"
    script: "./gradlew test"

  - stage: "Deploy to DockerHub"
    script:
    - ./gradlew clean jar
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - export REPO=emcmongoose/mongoose-storage-driver-kafka
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
    - export MONGOOSE_VERSION=$(cat build.gradle | grep "mongoose:" | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
    - docker build --build-arg MONGOOSE_VERSION=${MONGOOSE_VERSION} -f docker/Dockerfile -t $REPO:$COMMIT .
    - docker tag $REPO:$COMMIT $REPO:$TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO

  - stage: "Deploy to GitHub releases"
    deploy:
      skip_cleanup: true
      provider: releases
      api_key:
        secure: sCzZ0wCOqzln2oQXkDSPr4Jv77QfktDStWD90y9VSS1lDn1CIRuH8OfUSnfeOmXtuNrMs+ngZw3e7y8QCCYpykancVKOpszgG1pYxcqEdFT9Dj8jzJAJXJZGHrT4E9lHFl3seNH0cFC5BCi2EyHP0Vb1MVBJKwSS0jW8oD9KLdcFaBM45RfTWMt22qHFEI+Bl6ButvRaGmCXgHqQ9fqu2yRaELl+pLT+D44ZS9uhHzoc0htbjnVyQWcCzzLxcAlP6r4YFlTqxznfALf0TRBkgvqqWZ2SnS3u8sd/TQMZAuKwIUFvhHLbiBkfrKH4Ers/gPzoJR8pi1/9CE9gAwHxaGPn2bcxYV/tKnD3B3BweMzairpoHd6um0Uas7EF5E7gj01DsvdgiMfA9PlDeDylzce8rJh5ZNVHGxI6INDDdmDUzo76s9W0d8bYJ5+rz2IfU5rGMaPckaq/b3tBN4yfdHxBAUE1R+OSd2TQ6YP6JP04McpTQb+D6Yo/ealyyt3Jh8Pz8pFq93FN0awUlE6fhIDvTqweBJh4quvGtydzbNukszgro2KMhiqaDuV4pXuIfNwy6KaNZDPui9zgRjDbTWFUlKQq2r0/Gk6tLu2ezPtsdS/KXMJlFkg8TCNN5PlTAlSAu9m8uXzm8/SRfMJvtLQB8pwz/oSjY0UNXHII9KQ=
        file: "./build/libs/mongoose-storage-driver-kafka.jar"
      on:
        tags: true
