---
load:
  op:
    timeoutMillis: 300000
storage:
  driver:
    create:
      key:
        enabled: false
      headers: {}
    read:
      timeoutMillis: 10000
    request:
      size: 1048576
    buffer:
      memory: 33554432
    compression:
      type: none
  net:
    sndBuf: 131072
    rcvBuf: 32768
    linger: 0
    node:
      addrs:
        - 127.0.0.1
      port: 9092
