---
load:
  op:
    timeoutMillis: long
storage:
  driver:
    create:
      key:
        enabled: boolean
      headers: map
    read:
      timeoutMillis: long
    request:
      size: int
    buffer:
      memory: long
    compression:
      type: string
  net:
    sndBuf: int
    rcvBuf: int
    linger: int
    node:
      addrs: list
      port: int
